### ISSUE TITLE
when LI inserting the image, error happen

### ISSUE THREAD

**Issue by yogie89** [tonysamperi/endlessRiver#2]
Hi thanks for this script, it helps me a lot. anyway this animation style is interesting like apple site : https://www.apple.com/apple-tv-4k/.

but i have a problem when insering an img src inside <li> tag, the glitch is happen, i dont know why the image is not repeating like when you insert only a wording.

could you try, if you using image ? 

thanks

**Comment by tonysamperi** [comment]
You can put anything you want inside the &lt;li&gt; element, since it will be cloned entirely.
If you have a link, I can take I look, but the problem is in your CSS.

**Comment by yogie89** [comment]
https://www.xl.co.id/xlmobilsuperngobrol#Testimoni

please see this URL Tony.. THanks for the help

**Comment by tonysamperi** [comment]
I don't see anything wrong..
[bandicam 2017-09-19 16-18-11-751.zip](https://github.com/tonysamperi/endless-river/files/1314571/bandicam.2017-09-19.16-18-11-751.zip)
